apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-setup-job
spec:
  template:
    spec:
      containers:
      - name: setup
        image: busybox
        command: ["echo", "Initializing application..."]
      restartPolicy: Never
  backoffLimit: 2