apiVersion: v2
name: myapp
description: A Helm chart from scratch for DevOps course
type: application
version: 0.1.0
appVersion: "0.3.0"

dependencies:
  - name: nginx
    version: "15.x.x" # גרסת הצ'ארט (לא האימג')
    repository: "https://charts.bitnami.com/bitnami"