replicaCount: 2

image:
  repository: busybox
  tag: "1.36"
  args: ["sh", "-c", "echo Hello from BusyBox-yosef && sleep 3600"]

service:
  type: ClusterIP
  port: 5678

configData:
  message: "Configured via ConfigMap"
  port: "8080"

secretData:
  apiToken: "S3cr3tT0k3n"

appLabel: myapp
cronSchedule: "0 0 * * *" # פעם ביום בחצות

daemonset:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"